Update jekyll-gh-pages.yml

diff --git a/.github/workflows/jekyll-gh-pages.yml b/.github/workflows/jekyll-gh-pages.yml
--- a/.github/workflows/jekyll-gh-pages.yml
+++ b/.github/workflows/jekyll-gh-pages.yml
@@ -25,6 +25,16 @@ jobs:
         with:
           source: ./hrms-sys/views
           destination: https://ezra-6987.github.io/hrms/
+      - name: Check Content Size
+        run: |
+          content_size=$(du -sh ./hrms-sys | cut -f1)
+          echo "Content size: $content_size"
+          if [[ $content_size > 10G ]]; then
+            echo "Error: Content size exceeds 10GB limit."
+            exit 1
+          else
+            echo "Content size within limit."
+          fi
       - name: Clean up artifacts
         run: |
           # Remove hard links
@@ -51,6 +61,16 @@ jobs:
         with:
           name: hrms-artifact
           path: ./hrms-sys
+      - name: Check Content Size
+        run: |
+          content_size=$(du -sh ./hrms-sys | cut -f1)
+          echo "Content size: $content_size"
+          if [[ $content_size > 10G ]]; then
+            echo "Error: Content size exceeds 10GB limit."
+            exit 1
+          else
+            echo "Content size within limit."
+          fi
       - name: Deploy to GitHub Pages
         uses: actions/deploy-pages@v4
         with:
