Update jekyll-gh-pages.yml

diff --git a/.github/workflows/jekyll-gh-pages.yml b/.github/workflows/jekyll-gh-pages.yml
--- a/.github/workflows/jekyll-gh-pages.yml
+++ b/.github/workflows/jekyll-gh-pages.yml
@@ -20,27 +20,31 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
+
       - name: Build with Jekyll
         uses: actions/jekyll-build-pages@v1
         with:
           source: ./hrms-sys/views
           destination: ./hrms-sys/_site
+
       - name: Check Content Size
         run: |
           content_size=$(du -sb ./hrms-sys/_site | cut -f1)
-          echo "Content size: $(content_size bytes)"
+          echo "Content size: ${content_size} bytes"
           if [ $content_size -gt $((10 * 1024 * 1024 * 1024)) ]; then
             echo "Error: Content size exceeds 10GB limit."
             exit 1
           else
             echo "Content size within limit."
           fi
+
       - name: Clean up artifacts
         run: |
           # Remove hard links
           find ./hrms-sys/_site -type f -links +1 -exec rm {} +
           # Remove symlinks
           find ./hrms-sys/_site -type l -exec rm {} +
+
       - name: Upload artifact
         uses: actions/upload-artifact@v4
         with:
@@ -53,27 +57,31 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-      - name: Check Content Size
-        run: |
-         content_size=$(du -sb ./hrms-sys/_site | cut -f1)
-         echo "Content size: $(content_size bytes)"
-         if [ $content_size -gt $((10 * 1024 * 1024 * 1024)) ]; then
-           echo "Error: Content size exceeds 10GB limit."
-            exit 1
-          else
-            echo "Content size within limit."
-          fi
+
       - name: Download artifact
         uses: actions/download-artifact@v4
         with:
           name: hrms-artifact
           path: ./hrms-sys/_site
+
+      - name: Check Content Size
+        run: |
+          content_size=$(du -sb ./hrms-sys/_site | cut -f1)
+          echo "Content size: ${content_size} bytes"
+          if [ $content_size -gt $((10 * 1024 * 1024 * 1024)) ]; then
+            echo "Error: Content size exceeds 10GB limit."
+            exit 1
+          else
+            echo "Content size within limit."
+          fi
+
       - name: Clean up artifacts
-          run: |
-           # Remove hard links
-           find ./hrms-sys/_site -type f -links +1 -exec rm {} +
-           # Remove symlinks
-           find ./hrms-sys/_site -type l -exec rm {} +    
+        run: |
+          # Remove hard links
+          find ./hrms-sys/_site -type f -links +1 -exec rm {} +
+          # Remove symlinks
+          find ./hrms-sys/_site -type l -exec rm {} +
+
       - name: Deploy to GitHub Pages
         uses: actions/deploy-pages@v4
         with:
@@ -83,4 +91,3 @@ jobs:
           reporting_interval: 5000
           artifact_name: hrms-artifact
           preview: false
-  
