Update jekyll-gh-pages.yml

diff --git a/.github/workflows/jekyll-gh-pages.yml b/.github/workflows/jekyll-gh-pages.yml
--- a/.github/workflows/jekyll-gh-pages.yml
+++ b/.github/workflows/jekyll-gh-pages.yml
@@ -30,10 +30,10 @@ jobs:
           content_size=$(du -sb ./hrms-sys | cut -f1)
           echo "Content size: $content_size bytes"
           if [ $content_size -gt $((10 * 1024 * 1024 * 1024)) ]; then
-          echo "Error: Content size exceeds 10GB limit."
-          exit 1
+            echo "Error: Content size exceeds 10GB limit."
+            exit 1
           else
-          echo "Content size within limit."
+            echo "Content size within limit."
           fi
       - name: Clean up artifacts
         run: |
@@ -47,12 +47,24 @@ jobs:
           name: hrms-artifact
           path: ./hrms-sys
 
+  re-upload:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: hrms-artifact
+          path: ./hrms-sys
+
   deploy:
     environment:
       name: github-pages
       url: ${{ steps.build.outputs.artifacts_url }}
     runs-on: ubuntu-latest
-    needs: build
+    needs: re-upload
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -63,18 +75,18 @@ jobs:
           path: ./hrms-sys
       - name: Check Content Size
         run: |
-         content_size=$(du -sb ./hrms-sys | cut -f1)
+          content_size=$(du -sb ./hrms-sys | cut -f1)
           echo "Content size: $content_size bytes"
           if [ $content_size -gt $((10 * 1024 * 1024 * 1024)) ]; then
-          echo "Error: Content size exceeds 10GB limit."
-          exit 1
+            echo "Error: Content size exceeds 10GB limit."
+            exit 1
           else
-          echo "Content size within limit."
+            echo "Content size within limit."
           fi
       - name: Deploy to GitHub Pages
         uses: actions/deploy-pages@v4
         with:
-          token: ${{ secrets.GH_TOKEN}}
+          token: ${{ secrets.GH_TOKEN }}
           timeout: 600000
           error_count: 10
           reporting_interval: 5000
